GET http://localhost:8801/mock/nodes
Accept: application/json

###
GET http://localhost:8801/nodes
Accept: application/json

###
GET http://localhost:8801/mock/service/gateway
Accept: application/json

###
GET http://localhost:8801/mock/service/web
Accept: application/json

###
GET http://localhost:8801/services
Accept: application/json