location: prd # local / dev / prd
html:
  dir: './web'
  load: true
db:
  root: '/workspace/data/humpback.db'
  timeout: 5s
  sessionTimeout: 12h
  sessionGCInterval: 24h
  activityGCInterval: 24h
  activityRetentionDay: 120  #单位：天
  statisticsGCInterval: 24h
  statisticsRetentionDay: 32 #单位：天